<?php if(!@$_SESSION['loggedin']) header("Location: logout.php"); ?>
<!-- Start Page::View(home-mainpanel) -->
</tbody></table>
<table cellpadding="0" cellspacing="0">
<tr><td width="19" style="background:url(managedNOC/content_left_side.jpg);background-repeat:repeat-y;background-position:top left;">&nbsp;</td><td style="padding:19px 0;"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vehicula pellentesque sapien vel ullamcorper. Vivamus lectus lectus, consequat nec bibendum et, condimentum eget eros. In hac habitasse platea dictumst. Integer magna lectus, sollicitudin vel ullamcorper eget, bibendum vitae risus. Sed aliquam malesuada eros adipiscing cursus. Cras ultricies ante et eros ullamcorper ultricies. Ut vulputate vulputate purus, id viverra erat ultrices ut. Phasellus non lorem magna, vitae convallis dui. Sed turpis est, faucibus quis eleifend sit amet, consequat id velit. Aliquam a tellus id massa faucibus adipiscing eget at lacus. Donec ut interdum massa. Donec ornare, urna et luctus volutpat, enim mauris volutpat risus, quis vestibulum nunc nisl condimentum dui. Sed a risus eget elit volutpat volutpat eu sit amet ante. Suspendisse facilisis quam ultrices nibh molestie nec accumsan enim rhoncus. Praesent lacinia ante sed libero fringilla ultrices. Sed facilisis felis in eros faucibus a semper ante interdum. Nullam at orci sit amet leo rhoncus dapibus a nec magna.</p>
<p>Morbi eu nisi odio, vel ultrices ligula. Nunc libero sem, rhoncus dignissim semper in, iaculis nec dui. Nullam sit amet convallis quam. Vestibulum cursus mattis lacus, in rhoncus lacus hendrerit et. Suspendisse potenti. Nulla in eros sapien. Morbi a orci id nunc placerat ultrices. Maecenas lacinia, nibh vitae condimentum feugiat, tortor orci blandit risus, ut pretium eros diam a ante. Praesent lobortis porttitor ipsum nec dapibus. Ut laoreet commodo euismod. Mauris id lobortis metus. Pellentesque id dui velit, id malesuada nulla. Suspendisse enim nunc, semper vel fringilla bibendum, bibendum vitae magna. Morbi commodo, mi sit amet dignissim eleifend, justo lectus elementum velit, sed rhoncus libero erat id ante. Curabitur enim purus, elementum ac faucibus sed, mattis ut massa. Integer at nunc mi. Vestibulum quis est est, ac ultrices justo. Etiam rhoncus nisl et mauris fermentum tristique. Aenean ut erat enim, non tincidunt quam. Maecenas pharetra turpis ac elit ornare et luctus tellus sagittis.</p>
<p>Maecenas mattis cursus sapien non luctus. Donec eros tortor, tempus eget tempus sed, pellentesque nec enim. Etiam eget velit non erat adipiscing dictum at eget lorem. Ut nec turpis eros. Donec volutpat pretium fermentum. Proin id lectus tortor, ut sollicitudin lacus. In nec neque est. Integer vitae iaculis lacus. Aliquam pretium, diam eget vulputate porta, ligula purus ultricies augue, id dignissim turpis massa id lacus. Praesent elementum faucibus quam eu pharetra. Sed pulvinar, ipsum a fermentum vulputate, leo mi dignissim sapien, eget consectetur odio sem vitae lorem. Integer ut mi non turpis cursus eleifend ac et justo. Cras id nulla eu sapien pretium ornare at non odio. Proin mollis vestibulum dolor, id imperdiet sem blandit vel. Mauris in tortor nibh. Vestibulum iaculis dapibus urna, ut semper dui laoreet eu. Praesent tristique scelerisque tincidunt. Donec nec velit vitae leo aliquam cursus. Etiam vel urna nibh, eget aliquam justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>Proin consequat tellus et ipsum porttitor imperdiet. Cras fermentum dolor eget est lobortis euismod. Donec a lacus odio, eu ullamcorper nisi. Integer hendrerit enim et justo euismod suscipit. Vivamus fermentum neque in justo rutrum a consectetur velit molestie. Donec vitae risus metus. Morbi elementum metus sapien, quis porta eros. Ut scelerisque, ligula non suscipit dignissim, erat tortor mattis libero, venenatis volutpat felis ligula ac ante. Donec aliquet tincidunt pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In sem orci, hendrerit vitae placerat sed, sagittis eu nunc. Pellentesque sed ipsum nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Aenean ligula diam, lacinia cursus adipiscing ut, feugiat quis nunc. Donec quis eros lorem, sit amet ullamcorper mi. Nunc lobortis quam eget libero fermentum et porttitor justo dignissim. Ut non tortor ligula, nec eleifend lacus. Aliquam urna lectus, auctor a gravida ut, convallis id arcu.</p>
<p>Curabitur nec lorem et lectus sagittis sollicitudin nec eget quam. Ut quis sem nec ipsum varius venenatis. Sed purus tortor, posuere ac suscipit sit amet, mollis sed libero. Cras ut porta nisl. Etiam quis facilisis arcu. Fusce vitae sodales ante. Proin et mauris sit amet leo sodales suscipit. Suspendisse at neque venenatis diam tempus fringilla. Phasellus quis pellentesque sapien. Pellentesque et massa at eros hendrerit gravida. Sed ullamcorper tempus quam nec tincidunt.
<!-- End Page::View(home-mainpanel) -->
